debug: true
display_errors: true

triggers:
  nop:
    schema: https://specs.livecontracts.io/v1.0.0/action/nop/schema.json#
  http:
    schema: https://specs.livecontracts.io/v1.0.0/action/http/schema.json#

db:
  default:
    client: mongodb://localhost:27017
    database: lto_workflow_tests
