locale: en_US
debug: false
digest: required
noauth: false

triggers:
  nop:
    schema: https://specs.livecontracts.io/v1.0.0/action/nop/schema.json#

db:
  default:
    client: mongodb://localhost:27017
    database: lto_workflow

environment_variables:
  MONGO_DB: db.default.client
