debug: true
digest: optional
noauth: true

triggers:
  - schema: https://specs.livecontracts.io/v0.2.0/action/nop/schema.json#
    type: nop
  - schema: https://specs.livecontracts.io/v0.2.0/action/http/schema.json#
    type: http
  - schema: https://specs.livecontracts.io/v0.2.0/action/event/schema.json#
    type: event

lto:
  account:
    address: 3N2EVaqEToodweg371JNvGTMHxiS6Gsm9AH
    sign:
      secretkey: wJ4WH8dD88fSkNdFQRjaAhjFUZzZhV5yiDLDwNUnp6bYwRXrvWV8MJhQ9HL9uqMDG1n7XpTGZx7PafqaayQV8Rp
      publickey: FkU1XyfrCftc4pQKXCrrDyRLSnifX1SMvmx1CYiiyB3Y
    encrypt:
      secretkey: BnjFJJarge15FiqcxrB7Mzt68nseBXXR4LQ54qFBsWHG
      publickey: BVv1ZuE3gKFa6krwWJQwEmrLYUESuUabNCXgYTmCoBt6
  network: T

event_chain:
  url: http://localhost:4002/